draw_skull = \
  {'canvas1a': ['════════════════════════════════════════════', None, None,],
   'canvas1b': ['                                            ', None, None,],
   'canvas1c': ['              uu$$$$$$$$$$uu                ', None, None,],
   'canvas1d': ['          uu$$$$$$$$$$$$$$$$$uu             ', None, None,],
   'canvas1e': ['         u$$$$$$$$$$$$$$$$$$$$$u            ', None, None,],
   'canvas1f': ['        u$$$$$$$$$$$$$$$$$$$$$$$u           ', None, None,],
   'canvas1g': ['       u$$$$$$$$$$$$$$$$$$$$$$$$$u          ', None, None,],
   'canvas1h': ['       u$$$$$$$$$$$$$$$$$$$$$$$$$u          ', None, None,],
   'canvas1i': ['       u$$$$$$     $$$     $$$$$$u          ', None, None,],
   'canvas1k': ['        $$$$        u$u      $$$$u          ', None, None,],
   'canvas1l': ['        $$$u        u$u       u$$$          ', None, None,],
   'canvas1m': ['         $$$u       u$$$u     u$$$          ', None, None,],
   'canvas1n': ['         $$$$uu$$$uu_   _$$$uu$$$$          ', None, None,],
   'canvas1o': ['          $$$$$$$         $$$$$$$           ', None, None,],
   'canvas1p': ['             u$$$$$$$u$$$$$$$u              ', None, None,],
   'canvas1q': ['              u$##$$ $ $ $u$$u              ', None, None,],
   'canvas1r': ['    uuu       $$u$_$  $ $ $u$$        uuu   ', None, None,],
   'canvas1s': ['   u$$$$        $$$$$ u$u$u$$$       u$$$$  ', None, None,],
   'canvas1t': ['  $$$$$uu        $$$ $$$$$$       uu$$$$$$  ', None, None,],
   'canvas1v': ['════════════════════════════════════════════', None, None,],
   'canvas2a': ['══════════════════════════════════════════════════════', None, None,],
   'canvas2b': ['                                                      ', None, None,],
   'canvas2c': ['                                                      ', None, None,],
   'canvas2d': ['                                                      ', None, None,],
   'canvas2e': ['                                                      ', None, None,],
   'canvas2f': ['           Добро пожаловать в подземелье              ', None, None,],
   'canvas2g': ['                                                      ', None, None,],
   'canvas2h': ['                                                      ', None, None,],
   'canvas2i': ['                                                      ', None, None,],
   'canvas2k': ['                 "1" - новая игра                     ', None, None,],
   'canvas2l': ['                 "2" - продолжить                     ', None, None,],
   'canvas2m': ['                 "3" - выйти                          ', None, None,],
   'canvas2n': ['                                                      ', None, None,],
   'canvas2o': ['                                                      ', None, None,],
   'canvas2p': ['                                                      ', None, None,],
   'canvas2q': ['                                                      ', None, None,],
   'canvas2r': ['                                                      ', None, None,],
   'canvas2s': ['                                                      ', None, None,],
   'canvas2t': ['                                              (c)rypy ', None, None,],
   'canvas2v': ['══════════════════════════════════════════════════════', None, None,],}


